[project]
name = "telegram-mcp-summary"
version = "0.0.1"
description = "..."
readme = "README.md"
requires-python = ">=3.12.5"
dependencies = [
    "asyncpg>=0.30.0",
    "mcp[cli]>=1.6.0",
    "pyrogram>=2.0.106",
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
]
